# Generated by Django 5.2.1 on 2025-05-22 10:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_loginattempt_remove_user_is_temporary_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('host', models.CharField(help_text='SMTP server hostname', max_length=255)),
                ('port', models.IntegerField(default=587, help_text='SMTP server port')),
                ('username', models.CharField(help_text='SMTP username/email', max_length=255)),
                ('password', models.CharField(help_text='SMTP password', max_length=255)),
                ('use_tls', models.BooleanField(default=True, help_text='Use TLS encryption')),
                ('from_email', models.EmailField(help_text='Default sender email address', max_length=254)),
                ('from_name', models.CharField(blank=True, help_text='Default sender name', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active')),
                ('last_tested', models.DateTimeField(blank=True, help_text='Last time this configuration was successfully tested', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMTP Configuration',
                'verbose_name_plural': 'SMTP Configurations',
            },
        ),
    ]
