# Generated by Django 5.2.1 on 2025-05-22 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_loginattempt_remove_user_is_temporary_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
    ]
