# Generated by Django 5.2.1 on 2025-05-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_smtpconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smtpconfiguration',
            name='password',
            field=models.CharField(blank=True, help_text='SMTP password', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smtpconfiguration',
            name='username',
            field=models.CharField(blank=True, help_text='SMTP username/email', max_length=255, null=True),
        ),
    ]
