# Generated by Django 5.2.1 on 2025-05-22 12:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('auth', 'Authentication'), ('user', 'User Management'), ('security', 'Security'), ('system', 'System'), ('network', 'Network'), ('api', 'API Access'), ('admin', 'Admin Action'), ('data', 'Data Change')], max_length=20)),
                ('action', models.CharField(choices=[('auth_login', 'Login'), ('auth_logout', 'Logout'), ('auth_failed', 'Failed Authentication'), ('auth_password_change', 'Password Change'), ('auth_password_reset', 'Password Reset'), ('user_create', 'User Created'), ('user_update', 'User Updated'), ('user_delete', 'User Deleted'), ('user_role_change', 'Role Changed'), ('user_permission_change', 'Permission Changed'), ('user_profile_update', 'Profile Updated'), ('security_event', 'Security Event'), ('security_scan', 'Security Scan'), ('security_alert', 'Security Alert'), ('system_startup', 'System Startup'), ('system_shutdown', 'System Shutdown'), ('system_update', 'System Update'), ('system_config_change', 'Configuration Change'), ('network_scan', 'Network Scan'), ('network_device_added', 'Device Added'), ('network_device_updated', 'Device Updated'), ('network_device_removed', 'Device Removed'), ('network_device_status_change', 'Device Status Change'), ('api_access', 'API Access'), ('admin_action', 'Admin Action'), ('data_create', 'Data Created'), ('data_update', 'Data Updated'), ('data_delete', 'Data Deleted')], max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
                ('object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('object_id', models.CharField(blank=True, max_length=50, null=True)),
                ('object_name', models.CharField(blank=True, max_length=255, null=True)),
                ('retention_days', models.IntegerField(default=90)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application Log',
                'verbose_name_plural': 'Application Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'action'], name='api_applica_user_id_ee8ad2_idx'), models.Index(fields=['category'], name='api_applica_categor_9a7d11_idx'), models.Index(fields=['timestamp'], name='api_applica_timesta_e2ed89_idx'), models.Index(fields=['ip_address'], name='api_applica_ip_addr_bff5dc_idx'), models.Index(fields=['severity'], name='api_applica_severit_a7ac09_idx'), models.Index(fields=['object_type', 'object_id'], name='api_applica_object__158c4f_idx')],
            },
        ),
    ]
